var regexBrightness = /^(20|40|60|100)$/
var regexScrollMode = /^(overwrite|v_scroll|h_scroll)$/
var regexMoveto = /^(top_left|top_right|bottom_left|bottom_right)$/
var regexUnderline = /^(none|underline)$/
var regexMarquee = /^(walk|place)$/
var regexRow = /^([1-9]|1[0-9]|even|odd|all)$/
var regexSymbol = /^(qrcode_(model_[12]))$/
var regexLevel = /^(level_[lmqh]|default)$/
var regexQuietZone = /^(true|false)$/

var regexFont = /^(font_[a-e]|special_[ab])$/,
    regexAlign = /^(left|center|right)$/,
    regexColor = /^(none|color_[1-4])$/,
    regexFeed = /^(peeling|cutting|current_tof|next_tof)$/,
    regexMode = /^(mono|gray16)$/,
    regexBarcode = /^(upc_[ae]|[ej]an13|[ej]an8|code(39|93|128|128_auto)|itf|codabar|gs1_128|gs1_databar_(omnidirectional|truncated|limited|expanded))$/,
    regexHri = /^(none|above|below|both)$/,
    regexSymbol = /^(pdf417_(standard|truncated)|qrcode_(model_[12]|micro)|maxicode_mode_[2-6]|gs1_databar_(stacked(_omnidirectional)?|expanded_stacked)|azteccode_(fullrange|compact)|datamatrix_(square|rectangle_(8|12|16)))$/,
    regexLevel = /^(level_[0-8lmqh]|default)$/,
    regexLine = /^(thin|medium|thick)(_double)?$/,
    regexDirection = /^(left_to_right|bottom_to_top|right_to_left|top_to_bottom)$/,
    regexCut = /^(no_feed|feed|reserve)$/,
    regexDrawer = /^drawer_[12]$/,
    regexPulse = /^pulse_[1-5]00$/,
    regexPattern = /^(none|pattern_(10|[0-9a-e])|error|paper_end)$/,
    regexLayout = /^(receipt|label)(_bm)?$/